spring:
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: false
    banner-mode: console

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api/v1
  tomcat:
    accesslog:
      enabled: false

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      springframework: INFO

debug: false

database:
  username: Sparus
  password: rootroot
  bucket-name: IVTBucket
  connection-string: couchbase://127.0.0.1




