spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  config:
    import: config/security.yaml,config/database.yaml,config/setting-email.yaml
    resources:
      cache:
        cachecontrol:
          max-age: 180d

server:
  shutdown: graceful
  servlet:
    context-path: /api/v1


upload:
  path:
    default-dir: images
    partners: images/partners
    teachers: images/teachers
    reviews: images/reviews

debug: false
