spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  config:
    import: config/security.yaml,config/database.yaml,config/setting-email.yaml

server:
  shutdown: graceful
  servlet:
    context-path: /api/v1

upload:
  path:
    default-dir: images
    partners: images/partners
    teachers: images/teachers
    reviews: images/reviews

debug: false
