spring:
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
    banner-mode: console
  config:
    import: security.yaml,database.yaml,setting-email.yaml
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 180d

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api/v1

upload:
  path:
    partners: images/partners
    teachers: images/teachers
    reviews: images/reviews
