security:
  token:
    jwt:
      access:
      refresh:
      disposable:
      valid-time-access-second: 1800
      valid-time-refresh-second: 604800
      valid-time-disposable-second: 3600
      header-access-token: Authorization
      cookie-refresh-token: RefreshToken
      bearer: Bearer_
