spring:
  mail:
    username: ivt72@inbox.ru
    password: V97RC2HdCvWxWVKP4qYB
    port: 587
    host: smtp.mail.ru
    test-connection: false
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  username: Администрация сайта ИВТ
